# Generated by Django 2.0.2 on 2019-02-02 16:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('goods', '0003_auto_20190131_1306'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goodsimage',
            options={'verbose_name': '商品套图', 'verbose_name_plural': '商品套图'},
        ),
        migrations.AlterField(
            model_name='goods',
            name='is_hot',
            field=models.BooleanField(default=False, help_text='热销', verbose_name='是否热销'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='is_new',
            field=models.BooleanField(default=False, help_text='是否新的', verbose_name='是否新品'),
        ),
    ]
