# Generated by Django 2.0.2 on 2019-02-02 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('trade', '0004_auto_20190130_1424'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shoppingcart',
            options={'verbose_name': '购物车 ', 'verbose_name_plural': '购物车 '},
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='nonce_str',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='随机加密串'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='post_script',
            field=models.CharField(default='', max_length=200, verbose_name='订单留言'),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_goods',
                                    to='goods.Goods', verbose_name='商品名称'),
        ),
    ]
